apiVersion: apps/v1
kind: Deployment
metadata:
  name: anon-tech-deployment
  labels:
    app: anon-tech-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anon-tech-deployment
  template:
    metadata:
      labels:
        app: anon-tech-deployment
    spec:
      containers:
      - name: anon-tech
        image: anontechacr.azurecr.io/anon-tech:${{ github.sha }}
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: anon-tech-tf-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: anon-tech-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
