on: [push]
name: Linux_Container_Workflow
env:
    registry: ${{ secrets.registry }}
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/anon-tech:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/anon-tech:${{ github.sha }}
        - name: Set AKS context
          id: set-context
          uses: azure/aks-set-context@v3
          with:
            resource-group: '${{ secrets.RESOURCE_GROUP }}'
            cluster-name: '${{ secrets.cluster_name }}'
        - name: Setup kubectl
          id: install-kubectl
          uses: azure/setup-kubectl@v3
        - name: Deploy to AKS
          id: deploy-aks
          uses: Azure/k8s-deploy@v4
          with:
            namespace: 'default'
            manifests: |
              redis.yaml
            images: ${{ secrets.registry }}.azurecr.io/anon-tech:${{ github.sha }}
            pull: false 
